ALTER TABLE Horses
ADD CONSTRAINT stableID_constraint
FOREIGN KEY (stableID)
REFERENCES Stables
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE Horses
ADD CONSTRAINT trainerID_constraint
FOREIGN KEY (trainerID)
REFERENCES RacingPersons
ON DELETE SET NULL
ON UPDATE CASCADE;

ALTER TABLE Horses
ADD CONSTRAINT horseOwnerID_constraint
FOREIGN KEY (horseOwnerID)
REFERENCES RacingPersons
ON DELETE CASCADE
ON UPDATE RESTRICT;
